### ISSUE TITLE
NEI crash on a recipe involving Ender Pearl

### ISSUE THREAD

**Issue by zingewill** [PFAA-Updates/PFAA-Issues#44]
All I really know about this crash is what is contained in the crash log, and that the culprit recipe contains an Ender Pearl.
[crash-2024-12-22_11.19.11-client.txt](https://github.com/user-attachments/files/18223143/crash-2024-12-22_11.19.11-client.txt)

**Comment by ChrisJStone** [comment]
Initial when I cycled through the recipe's I didn't get a crash second time I did so it might be a intermittent error. Also found this in my crash log. Might be related.

[13:25:38] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: net.minecraft.item.ItemBlock@169874d4
[13:25:38] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: net.minecraft.item.ItemBlock@45672b82
[13:25:38] [Client thread/INFO] [NotEnoughItems]: Loading 'collapsibleitems.cfg' file D:\MultiMC\instances\Evaryan\.minecraft\config\NEI\collapsibleitems.cfg
[13:25:38] [ForkJoinPool.commonPool-worker-3/INFO] [neiintegration]: Loading integration: Minecraft / Forge
[13:25:38] [ForkJoinPool.commonPool-worker-1/INFO] [OpenMods]: openblocks.NEIOpenBlocksConfig.loadConfig(NEIOpenBlocksConfig.java:40): OpenBlocks NEI Integration loaded successfully
[13:25:38] [ForkJoinPool.commonPool-worker-7/INFO] [PneumaticCraft]: Initializing PneumaticCraft built-in NEI plugin...
[13:25:39] [ForkJoinPool.commonPool-worker-5/ERROR] [NotEnoughItems]: Failed to Load blusunrize.immersiveengineering.client.nei.NEIConfig
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/client/nei/NEIArcFurnaceHandler (wrong name: NEIArcFurnaceHandlerAlloying)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_411]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_411]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_411]
	at blusunrize.immersiveengineering.client.nei.NEIArcFurnaceHandler$ProxyClassLoader.findClass(NEIArcFurnaceHandler.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_411]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_411]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_411]
	at blusunrize.immersiveengineering.client.nei.NEIArcFurnaceHandler$ProxyClassLoader.findClass(NEIArcFurnaceHandler.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_411]
	at blusunrize.immersiveengineering.client.nei.NEIArcFurnaceHandler.createSubHandler(NEIArcFurnaceHandler.java:60) ~[?:?]
	at blusunrize.immersiveengineering.client.nei.NEIConfig.loadConfig(NEIConfig.java:39) ~[?:?]
	at codechicken.nei.NEIClientConfig$16.lambda$run$0(NEIClientConfig.java:743) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_411]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) [?:1.8.0_411]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_411]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_411]

**Comment by ChrisJStone** [comment]
Marking this as resolved and closed as fix is merged upstream.
https://github.com/GTNewHorizons/NotEnoughItems/pull/589
